### ISSUE TITLE
500 Error on userSettingPage

### ISSUE THREAD

**Issue by JPGarCar** [JPGarCar/HORS#15]
[2021-01-15 10:52:43,545] ERROR in app: Exception on /userSettingsPage [GET]
Traceback (most recent call last):
  File "c:\users\juapg\pythonenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\juapg\pythonenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\juapg\pythonenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\juapg\pythonenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\juapg\pythonenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\juapg\pythonenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\juapg\PycharmProjects\HORS\app.py", line 440, in userSettingsPage
    ### similiar to signOut but different unknown use
  File "c:\users\juapg\pythonenv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\juapg\pythonenv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\juapg\pythonenv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\juapg\pythonenv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\juapg\pythonenv\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\juapg\pythonenv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\juapg\pythonenv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)

**Comment by JPGarCar** [comment]
So it turns out we dont have the user_settingsPage.html. So we will have to do it all again!
